-- Neovim treesitter
return {
        "nvim-treesitter/nvim-treesitter",
        lazy = true,
        opts = {
            ensure_installed = {
                "vim",
                "c",
                "query",
                "vimdoc",
                "ada",
                "agda",
                "angular",
                "apex",
                "astro",
                "bass",
                "bibtex",
                "bicep",
                "c_sharp",
                "capnp",
                "clojure",
                "cmake",
                "comment",
                "csv",
                "css",
                "cpp",
                "dart",
                "diff",
                "dot",
                "dockerfile",
                "doxygen",
                "elixir",
                "erlang",
                "fennel",
                "fish",
                "fortran",
                "git_config",
                "git_rebase",
                "gitcommit",
                "go",
                "gomod",
                "gosum",
                "gpg",
                "graphql",
                "groovy",
                "haskell",
                "haskell_persistent",
                "hcl",
                "hjson",
                "html",
                "http",
                "hurl",
                "java",
                "json",
                "jsdoc",
                "julia",
                "kotlin",
                "luau",
                "luadoc",
                "make",
                "matlab",
                "meson",
                "nim",
                "nix",
                "org",
                "pascal",
                "perl",
                "phpdoc",
                "prisma",
                "psv",
                "pug",
                "ql",
                "robot",
                "ruby",
                "scala",
                "scss",
                "solidity",
                "svelte",
                "swift",
                "sxhkdrc",
                "templ",
                "terraform",
                "toml",
                "ninja",
                "regex",
                "lua",
                "bash",
                "markdown",
                "markdown_inline",
                "python",
                "rust",
                "sql",
                "php",
                "javascript",
                "http",
                "json",
                "latex",
                "commonlisp",
                "tsv",
                "tsx",
                "twig",
                "typescript",
                "typoscript",
                "udev",
                "usd",
                "vala",
                "vue",
                "vimdoc",
                "xml",
                "yaml",
                "zig",
                "zathurarc"
            },
            highlight = {
                enable = true,
                additional_vim_regex_highlighting = {
                    "php",
                    "markdown",
                    "rust",
                    "python"
                },
            },
            rainbow = {
                enable = true,
                extended_mode = true,
            },
            incremental_selection = {
                enable = false,
                keymaps = {
                    init_selection = '<CR>',
                    scope_incremental = '<CR>',
                    node_incremental = '<TAB>',
                    node_decremental = '<S-TAB>',
                }
            },
            indent = {
                enable = true,
                disable = { "python" },
            },
            tree_docs = {
                enable = true,
            }
        }
    },
    { "akinsho/toggleterm.nvim", version = "*", config = true },
    {
        "folke/todo-comments.nvim",
        dependecies = "nvim-lua/plenary.nvim",
        opts = {
            signs = true,
            sign_priority = 8,
            keywords = {
                FIX = {
                    icon = " ",
                    color = "error",
                    alt = { "FIXME", "BUG", "FIXIT", "ISSUE" },
                },
                TODO = { icon = " ", color = "info" },
                HACK = { icon = " ", color = "warning" },
                WARN = {
                    icon = " ",
                    color = "warning",
                    alt = { "WARNING", "XXX" }
                },
                PERF = {
                    icon = " ",
                    alt = { "OPTIM", "PERFORMANCE", "OPTIMIZE" }
                },
                NOTE = { icon = " ", color = "hint", alt = { "INFO" } },
                TEST = {
                    icon = "⏲ ",
                    color = "test",
                    alt = { "TESTING", "PASSED", "FAILED" }
                },
            },
            merge_keywords = true,
            highlight = {
                before = "",
                keyword = "wide",
                after = "fg",
                pattern = [[.*<(KEYWORDS)\s*:]],
                comments_only = true,
                max_line_len = 400,
                exclude = {},
            },
            colors = {
                error = { "DiagnosticError", "ErrorMsg", "#DC2626" },
                warning = { "DiagnosticWarning", "WarningMsg", "#FBBF24" },
                info = { "DiagnosticInfo", "#2563EB" },
                hint = { "DiagnosticHint", "#10B981" },
                default = { "Identifier", "#7C3AED" },
                test = { "Identifier", "#FF00FF" },
            },
            search = {
                command = "rg",
                args = {
                    "--color=never",
                    "--no-heading",
                    "--with-filename",
                    "--line-number",
                    "--column",
                },
                pattern = [[\b(KEYWORDS):]],
            },
        }
    }
